#!/bin/bash

BIN_DIR=~/.local/bin
CONFIG_DIR=~/.config

[ ! -f ~/.zshrc ] && ln .zshrc ~/.zshrc
[ ! -f ~/.xprofile ] && ln .xprofile ~/.xprofile
[ ! -f ~/.vimrc ] && ln .vimrc ~/.vimrc && ln .vimrc ~/.config/nvim/init.vim
[ ! -f ~/.Xresources ] && cp -p .Xresources .Xdefaults && ln .Xresources ~/.Xresources && xrdb ~/.Xresources

mkdir -p ${BIN_DIR}/
ln -f .local/bin/* ${BIN_DIR}/

cp -rf .config/* ${CONFIG_DIR}/
