#!/bin/sh


user_info="${USER}@$(hostname)"
delim="|"

bar_status() {
	sed "s/down//;s/up/🌎/" /sys/class/net/e*/operstate && echo "$delim"
	printf "${user_info} $delim "
	date '+%a %d %b %Y %H:%M:%S'
}


while :; do
	xsetroot -name "$(bar_status | tr '\n' ' ')"
	sleep 1
done
